name: "CI: Security Gitleaks"

on:
  pull_request:
    branches: [$default-branch]

jobs:
  gitleaks:
    name: Run Gitleaks
    uses: Coalfire-CF/Actions/.github/workflows/ci-security-gitleaks.yml@e833f409d1d1fd8014f3de1efd077785d3dae460 # v1.5.0
