name: "CI: Security Gitleaks"

on:
  pull_request:
    branches: [$default-branch]

jobs:
  gitleaks:
    name: Run Gitleaks
    uses: Coalfire-CF/Actions/.github/workflows/ci-security-gitleaks.yml@7471e346de7b74bcd66188d9a5009b1580db0950 # v1.4.0
