name: "CI: Terraform validate"

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"
      - "**/terraform/**"

jobs:
  terraform-validate:
    name: Validate Terraform
    uses: Coalfire-CF/Actions/.github/workflows/ci-terraform-validate.yml@e833f409d1d1fd8014f3de1efd077785d3dae460 # v1.5.0
    with:
      terraform_version: "1.13.3"
    secrets: inherit
